### ISSUE TITLE
Issue with theme

### ISSUE THREAD

**Issue by r3k2** [RaphGL/rofi#12]
for the last couple weeks I had to remove this from rofi because I was getting css errors.
"Failed to resolve variable 'urgent-foreground' in: `element normal urgent { text color: var (urgent foreground);}`
something similar ignore typos because I had to copy this manually.

**Comment by r3k2** [comment]
@avelino @vigo @DamianK-zz Hello any one had time to check on this? Im sure is something super easy to fix.

**Comment by avelino** [comment]
unfortunately I can't help you with the solution to this problem - I am not a rofi user, I'm flagging the @RaphGL (maintainer of this project) to support us with the problem

**Comment by RaphGL** [comment]
Hi, I'm the maintainer of the project. 

I haven't had time to look into it recently, this has been a recurring problem in the last few months, Rofi has constantly been changing it's API so the theme is constantly breaking. 

I'll see what has to be changed.

**Comment by r3k2** [comment]
@RaphGL thank you, let me know if you can fix it so I do a pull with the changes. thanks

**Comment by RaphGL** [comment]
Hi, @r3k2. Sorry for the very late reply. I've tried it on rofi 1.7.3 and everything seems to be working fine. does the problem still persist for you?

**Comment by alexeightsix** [comment]
I started getting this error today on rofi 1.7.4-1

**Comment by alexeightsix** [comment]
I fixed it by defining  `urgent-foreground: @drac-red;` to the list of variables

@RaphGL  Edit /usr/share/rofi/themes/dracula2.rasi or /usr/share/rofi/themes/dracula2.rasi  depending on which one you're using as root
