### ISSUE TITLE
Rofi 1.7.0-1 breaks this theme

### ISSUE THREAD

**Issue by brandflake11** [RaphGL/rofi#3]
Hello,
I am on Artix Linux (Arch Linux without systemd) and it seems a new [update to rofi broke the dracula theme](https://ibb.co/gdmSxC5). The theme is still kind of working, however, the foreground text is black instead of white (or a lighter color) like it should probably be, making rofi really hard to read.

**Comment by touhidulshawan** [comment]
Hi, there
I have also face this issue. But I fixed it with these steps
- make a dracula.rasi file in `/usr/share/rofi/themes/` and copy all content of `config.rasi` from this repo
- remove `#` from all selector
- add these line 
```
element-text {
    background-color: inherit;
    text-color:       inherit;
}
```
- run `rofi-theme-selector` from terminal and select dracula 😃

**Comment by brandflake11** [comment]
@touhidulShawan Thank you for the fix. We need to get these four lines merged into the main code now.

**Comment by touhidulshawan** [comment]
@brandflake11 I have created a pull request #4 with the fixes. If it gets merged then the problem will be solved.

**Comment by TheOmegaCarrot** [comment]
@touhidulShawan That fix worked for me!
Thanks a lot!

**Comment by RaphGL** [comment]
PR #5 has been merged, fixing the issue. Thanks @1478zhcy and everyone that helped.
