### ISSUE TITLE
light background after theme intallation

### ISSUE THREAD

**Issue by purrrkin** [RaphGL/rofi#7]
I wonder how can i fix these light lines?
![Screenshot from 2021-12-10 13-29-13](https://user-images.githubusercontent.com/46737360/145643712-03e388b9-547d-4b2a-ac61-3372f0fb03a7.png)

**Comment by aratare-jp** [comment]
Having same problem here.

**Comment by Lighters73** [comment]
Rofi was recently updated so I am guessing that has caused the problem

**Comment by burrhole** [comment]
the issue is that `background` in the theme parser has been changed to `background-color`, and at the end it needs 
```
element-text, element-icon {
    background-color: inherit;
    text-color: inherit;
}
```
Here's a diff:
```diff
6c6
<     background: #282a36;
---
>     background-color: #282a36;
121a122,125
> }
> element-text, element-icon {
>     background-color: inherit;
>     text-color: inherit;
```

**Comment by purrrkin** [comment]
> the issue is that `background` in the theme parser has been changed to `background-color`, and at the end it needs
> 
> ```
> element-text, element-icon {
>     background-color: inherit;
>     text-color: inherit;
> }
> ```
> 
> Here's a diff:
> 
> ```diff
> 6c6
> <     background: #282a36;
> ---
> >     background-color: #282a36;
> 121a122,125
> > }
> > element-text, element-icon {
> >     background-color: inherit;
> >     text-color: inherit;
> ```

That worked perfectly!

**Comment by purrrkin** [comment]
Now it looks a bit differently, but still broken. I just downloaded the fresh config:
![PXL_20220120_190928269 MP](https://user-images.githubusercontent.com/46737360/150406669-dc606597-4889-4367-a293-47ea718af7eb.jpg)

**Comment by lordlabuckdas** [comment]
Same issue as @purrrkin.

`Rofi Version: 1.7.2`
